name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: debian

    strategy:
      matrix:
        node:
          - 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install native deps
        run: |
          sudo apt update;
          sudo apt install -y \
            build-essential \
            pkg-config \
            libx11-dev \
            libxtst-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxi-dev \
            libxext-dev \
            libxfixes-dev \
            libxkbfile-dev \
            libpng-dev \
            xvfb;

      - name: Install
        run: |
          npm ci || npm install;

      - name: Test
        run: |
          xvfb-run -a npm test;
